export const data = [{
    "id": 1,
    "name": "Shary",
    "blood_group": "AB-",
    "gender": "Male",
    "city": "Rawalpindi",
    "age": 20,
    "number": "324",
    "address": "Faisalabad"
  }, {
    "id": 2,
    "name": "Abdullah",
    "blood_group": "O-",
    "gender": "Male",
    "city": "Karachi",
    "age": 20,
    "number": "423",
    "address": "Punjab"
  }, {
    "id": 3,
    "name": "Waqar",
    "blood_group": "B+",
    "gender": "Male",
    "city": "Lahore",
    "age": 20,
    "number": "567",
    "address": "Pakistan"
  }, {
    "id": 4,
    "name": "Wassaf",
    "blood_group": "A-",
    "gender": "Male",
    "city": "Lahore",
    "age": 20,
    "number": "324",
    "address": "Pakistan"
  }, {
    "id": 5,
    "name": "Shary",
    "blood_group": "O+",
    "gender": "Male",
    "city": "Islamabad",
    "age": 13,
    "number": "867",
    "address": "Punjab"
  }, {
    "id": 6,
    "name": "Zain",
    "blood_group": "AB-",
    "gender": "Male",
    "city": "Rawalpindi",
    "age": 25,
    "number": "867",
    "address": "Punjab"
  }, {
    "id": 7,
    "name": "Waqar",
    "blood_group": "B+",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 26,
    "number": "234",
    "address": "Punjab"
  }, {
    "id": 8,
    "name": "Shary",
    "blood_group": "B-",
    "gender": "Male",
    "city": "Islamabad",
    "age": 25,
    "number": "867",
    "address": "Punjab"
  }, {
    "id": 9,
    "name": "Mohsin",
    "blood_group": "O+",
    "gender": "Male",
    "city": "Faisalabad",
    "age": 25,
    "number": "79789",
    "address": "Pakistan"
  }, {
    "id": 10,
    "name": "Basit",
    "blood_group": "B+",
    "gender": "Male",
    "city": "Lahore",
    "age": 15,
    "number": "8",
    "address": "Pakistan"
  }, {
    "id": 11,
    "name": "Wassaf",
    "blood_group": "O+",
    "gender": "Male",
    "city": "Islamabad",
    "age": 20,
    "number": "",
    "address": "Punjab"
  }, {
    "id": 12,
    "name": "Ghous",
    "blood_group": "O+",
    "gender": "Male",
    "city": "Islamabad",
    "age": 20,
    "number": "3",
    "address": "Pakistan"
  }, {
    "id": 13,
    "name": "Shary",
    "blood_group": "B+",
    "gender": "Male",
    "city": "Islamabad",
    "age": 20,
    "number": "5",
    "address": "Pakistan"
  }, {
    "id": 14,
    "name": "Waqar",
    "blood_group": "A+",
    "gender": "Male",
    "city": "Lahore",
    "age": 25,
    "number": "79",
    "address": "Pakistan"
  }, {
    "id": 15,
    "name": "Basit",
    "blood_group": "A+",
    "gender": "Male",
    "city": "Faisalabad",
    "age": 13,
    "number": "324",
    "address": "Punjab"
  }, {
    "id": 16,
    "name": "Waqar",
    "blood_group": "AB+",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 20,
    "number": "4",
    "address": "Punjab"
  }, {
    "id": 17,
    "name": "Abdullah",
    "blood_group": "AB-",
    "gender": "Male",
    "city": "Islamabad",
    "age": 13,
    "number": "867",
    "address": "Punjab"
  }, {
    "id": 18,
    "name": "Shary",
    "blood_group": "O-",
    "gender": "Male",
    "city": "Islamabad",
    "age": 13,
    "number": "8",
    "address": "Punjab"
  }, {
    "id": 19,
    "name": "Shary",
    "blood_group": "O-",
    "gender": "Male",
    "city": "Multan",
    "age": 26,
    "number": "324",
    "address": "Punjab"
  }, {
    "id": 20,
    "name": "Wasif",
    "blood_group": "AB+",
    "gender": "Male",
    "city": "Multan",
    "age": 15,
    "number": "8",
    "address": "Punjab"
  }, {
    "id": 21,
    "name": "Waqar",
    "blood_group": "AB-",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 13,
    "number": "234",
    "address": "Punjab"
  }, {
    "id": 22,
    "name": "Sajawal",
    "blood_group": "AB+",
    "gender": "Male",
    "city": "Karachi",
    "age": 26,
    "number": "324",
    "address": "Faisalabad"
  }, {
    "id": 23,
    "name": "Ahmad",
    "blood_group": "AB+",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 15,
    "number": "546",
    "address": "Pakistan"
  }, {
    "id": 24,
    "name": "Basit",
    "blood_group": "AB+",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 20,
    "number": "",
    "address": "Punjab"
  }, {
    "id": 25,
    "name": "Ghous",
    "blood_group": "A-",
    "gender": "Male",
    "city": "Multan",
    "age": 15,
    "number": "",
    "address": "Faisalabad"
  }, {
    "id": 26,
    "name": "Ghous",
    "blood_group": "B+",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 13,
    "number": "3",
    "address": "Pakistan"
  }, {
    "id": 27,
    "name": "Shary",
    "blood_group": "A+",
    "gender": "Male",
    "city": "Lahore",
    "age": 15,
    "number": "3",
    "address": "Pakistan"
  }, {
    "id": 28,
    "name": "Wasif",
    "blood_group": "AB+",
    "gender": "Male",
    "city": "Rawalpindi",
    "age": 25,
    "number": "324",
    "address": "Pakistan"
  }, {
    "id": 29,
    "name": "Aslam",
    "blood_group": "AB+",
    "gender": "Male",
    "city": "Faisalabad",
    "age": 20,
    "number": "8",
    "address": "Pakistan"
  }, {
    "id": 30,
    "name": "Ghous",
    "blood_group": "AB-",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 20,
    "number": "867",
    "address": "Punjab"
  }, {
    "id": 31,
    "name": "Shary",
    "blood_group": "O-",
    "gender": "Male",
    "city": "Multan",
    "age": 20,
    "number": "423",
    "address": "Punjab"
  }, {
    "id": 32,
    "name": "Ali",
    "blood_group": "AB-",
    "gender": "Male",
    "city": "Faisalabad",
    "age": 20,
    "number": "324",
    "address": "Faisalabad"
  }, {
    "id": 33,
    "name": "Ghulam",
    "blood_group": "O+",
    "gender": "Male",
    "city": "Karachi",
    "age": 15,
    "number": "234",
    "address": "Punjab"
  }, {
    "id": 34,
    "name": "Ghous",
    "blood_group": "AB+",
    "gender": "Male",
    "city": "Multan",
    "age": 25,
    "number": "324",
    "address": "Punjab"
  }, {
    "id": 35,
    "name": "Ali",
    "blood_group": "B-",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 26,
    "number": "32",
    "address": "Faisalabad"
  }, {
    "id": 36,
    "name": "Shary",
    "blood_group": "A-",
    "gender": "Male",
    "city": "Karachi",
    "age": 13,
    "number": "234",
    "address": "Pakistan"
  }, {
    "id": 37,
    "name": "Ali",
    "blood_group": "B+",
    "gender": "Male",
    "city": "Rawalpindi",
    "age": 20,
    "number": "324",
    "address": "Punjab"
  }, {
    "id": 38,
    "name": "Wasif",
    "blood_group": "O+",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 26,
    "number": "324",
    "address": "Punjab"
  }, {
    "id": 39,
    "name": "Wassaf",
    "blood_group": "O+",
    "gender": "Male",
    "city": "Karachi",
    "age": 25,
    "number": "567",
    "address": "Punjab"
  }, {
    "id": 40,
    "name": "Ali",
    "blood_group": "B-",
    "gender": "Male",
    "city": "Faisalabad",
    "age": 26,
    "number": "324",
    "address": "Punjab"
  }, {
    "id": 41,
    "name": "Ahmad",
    "blood_group": "A+",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 26,
    "number": "32",
    "address": "Faisalabad"
  }, {
    "id": 42,
    "name": "Basit",
    "blood_group": "B-",
    "gender": "Male",
    "city": "Islamabad",
    "age": 26,
    "number": "867",
    "address": "Punjab"
  }, {
    "id": 43,
    "name": "Wassaf",
    "blood_group": "B-",
    "gender": "Male",
    "city": "Rawalpindi",
    "age": 25,
    "number": "867",
    "address": "Faisalabad"
  }, {
    "id": 44,
    "name": "Shary",
    "blood_group": "B+",
    "gender": "Male",
    "city": "Islamabad",
    "age": 25,
    "number": "6",
    "address": "Punjab"
  }, {
    "id": 45,
    "name": "Sajawal",
    "blood_group": "B-",
    "gender": "Male",
    "city": "Islamabad",
    "age": 20,
    "number": "4",
    "address": "Faisalabad"
  }, {
    "id": 46,
    "name": "Shary",
    "blood_group": "AB+",
    "gender": "Male",
    "city": "Faisalabad",
    "age": 26,
    "number": "867",
    "address": "Faisalabad"
  }, {
    "id": 47,
    "name": "Asad",
    "blood_group": "A+",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 25,
    "number": "867",
    "address": "Pakistan"
  }, {
    "id": 48,
    "name": "Basit",
    "blood_group": "AB+",
    "gender": "Male",
    "city": "Multan",
    "age": 25,
    "number": "423",
    "address": "Pakistan"
  }, {
    "id": 49,
    "name": "Shary",
    "blood_group": "AB+",
    "gender": "Male",
    "city": "Karachi",
    "age": 15,
    "number": "867",
    "address": "Faisalabad"
  }, {
    "id": 50,
    "name": "Shary",
    "blood_group": "AB+",
    "gender": "Male",
    "city": "Multan",
    "age": 25,
    "number": "32423",
    "address": "Faisalabad"
  }, {
    "id": 51,
    "name": "Ali",
    "blood_group": "A+",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 25,
    "number": "5",
    "address": "Faisalabad"
  }, {
    "id": 52,
    "name": "Mohsin",
    "blood_group": "A+",
    "gender": "Male",
    "city": "Rawalpindi",
    "age": 15,
    "number": "79",
    "address": "Punjab"
  }, {
    "id": 53,
    "name": "Ahmad",
    "blood_group": "A-",
    "gender": "Male",
    "city": "Islamabad",
    "age": 15,
    "number": "3",
    "address": "Faisalabad"
  }, {
    "id": 54,
    "name": "Waqar",
    "blood_group": "O+",
    "gender": "Male",
    "city": "Rawalpindi",
    "age": 20,
    "number": "32",
    "address": "Pakistan"
  }, {
    "id": 55,
    "name": "Ahmad",
    "blood_group": "AB-",
    "gender": "Male",
    "city": "Multan",
    "age": 25,
    "number": "6",
    "address": "Punjab"
  }, {
    "id": 56,
    "name": "Shary",
    "blood_group": "B-",
    "gender": "Male",
    "city": "Karachi",
    "age": 13,
    "number": "423",
    "address": "Punjab"
  }, {
    "id": 57,
    "name": "Wasif",
    "blood_group": "AB-",
    "gender": "Male",
    "city": "Multan",
    "age": 20,
    "number": "5",
    "address": "Faisalabad"
  }, {
    "id": 58,
    "name": "Ghulam",
    "blood_group": "B-",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 25,
    "number": "79",
    "address": "Pakistan"
  }, {
    "id": 59,
    "name": "Umar",
    "blood_group": "A+",
    "gender": "Male",
    "city": "Lahore",
    "age": 20,
    "number": "4",
    "address": "Punjab"
  }, {
    "id": 60,
    "name": "Ghous",
    "blood_group": "AB-",
    "gender": "Male",
    "city": "Rawalpindi",
    "age": 20,
    "number": "32",
    "address": "Faisalabad"
  }, {
    "id": 61,
    "name": "Wassaf",
    "blood_group": "A-",
    "gender": "Male",
    "city": "Lahore",
    "age": 20,
    "number": "4",
    "address": "Punjab"
  }, {
    "id": 62,
    "name": "Asad",
    "blood_group": "O+",
    "gender": "Male",
    "city": "Rawalpindi",
    "age": 15,
    "number": "7",
    "address": "Faisalabad"
  }, {
    "id": 63,
    "name": "Ghulam",
    "blood_group": "O+",
    "gender": "Male",
    "city": "Lahore",
    "age": 15,
    "number": "",
    "address": "Punjab"
  }, {
    "id": 64,
    "name": "Aslam",
    "blood_group": "O-",
    "gender": "Male",
    "city": "Lahore",
    "age": 20,
    "number": "79789",
    "address": "Faisalabad"
  }, {
    "id": 65,
    "name": "Ghulam",
    "blood_group": "AB+",
    "gender": "Male",
    "city": "Karachi",
    "age": 25,
    "number": "567",
    "address": "Pakistan"
  }, {
    "id": 66,
    "name": "Abdullah",
    "blood_group": "O+",
    "gender": "Male",
    "city": "Lahore",
    "age": 25,
    "number": "4",
    "address": "Pakistan"
  }, {
    "id": 67,
    "name": "Asad",
    "blood_group": "O+",
    "gender": "Male",
    "city": "Islamabad",
    "age": 20,
    "number": "8",
    "address": "Faisalabad"
  }, {
    "id": 68,
    "name": "Wasif",
    "blood_group": "A+",
    "gender": "Male",
    "city": "Multan",
    "age": 20,
    "number": "8",
    "address": "Punjab"
  }, {
    "id": 69,
    "name": "Ali",
    "blood_group": "O+",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 25,
    "number": "",
    "address": "Pakistan"
  }, {
    "id": 70,
    "name": "Ahmad",
    "blood_group": "O-",
    "gender": "Male",
    "city": "Multan",
    "age": 26,
    "number": "8",
    "address": "Pakistan"
  }, {
    "id": 71,
    "name": "Shary",
    "blood_group": "A+",
    "gender": "Male",
    "city": "Multan",
    "age": 20,
    "number": "",
    "address": "Punjab"
  }, {
    "id": 72,
    "name": "Mohsin",
    "blood_group": "B-",
    "gender": "Male",
    "city": "Rawalpindi",
    "age": 20,
    "number": "546",
    "address": "Pakistan"
  }, {
    "id": 73,
    "name": "Wasif",
    "blood_group": "B+",
    "gender": "Male",
    "city": "Faisalabad",
    "age": 26,
    "number": "",
    "address": "Punjab"
  }, {
    "id": 74,
    "name": "Shary",
    "blood_group": "AB-",
    "gender": "Male",
    "city": "Karachi",
    "age": 25,
    "number": "32",
    "address": "Faisalabad"
  }, {
    "id": 75,
    "name": "Aslam",
    "blood_group": "O-",
    "gender": "Male",
    "city": "Islamabad",
    "age": 15,
    "number": "4",
    "address": "Pakistan"
  }, {
    "id": 76,
    "name": "Aslam",
    "blood_group": "O-",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 26,
    "number": "324",
    "address": "Punjab"
  }, {
    "id": 77,
    "name": "Zain",
    "blood_group": "AB+",
    "gender": "Male",
    "city": "Karachi",
    "age": 20,
    "number": "",
    "address": "Punjab"
  }, {
    "id": 78,
    "name": "Zain",
    "blood_group": "B+",
    "gender": "Male",
    "city": "Multan",
    "age": 13,
    "number": "324",
    "address": "Punjab"
  }, {
    "id": 79,
    "name": "Waqar",
    "blood_group": "B-",
    "gender": "Male",
    "city": "Multan",
    "age": 20,
    "number": "",
    "address": "Faisalabad"
  }, {
    "id": 80,
    "name": "Shary",
    "blood_group": "AB-",
    "gender": "Male",
    "city": "Rawalpindi",
    "age": 20,
    "number": "324",
    "address": "Faisalabad"
  }, {
    "id": 81,
    "name": "Waqar",
    "blood_group": "B+",
    "gender": "Male",
    "city": "Karachi",
    "age": 26,
    "number": "32",
    "address": "Pakistan"
  }, {
    "id": 82,
    "name": "Abdullah",
    "blood_group": "B-",
    "gender": "Male",
    "city": "Lahore",
    "age": 26,
    "number": "4",
    "address": "Faisalabad"
  }, {
    "id": 83,
    "name": "Mohsin",
    "blood_group": "B+",
    "gender": "Male",
    "city": "Islamabad",
    "age": 13,
    "number": "79789",
    "address": "Pakistan"
  }, {
    "id": 84,
    "name": "Asad",
    "blood_group": "A+",
    "gender": "Male",
    "city": "Multan",
    "age": 20,
    "number": "",
    "address": "Punjab"
  }, {
    "id": 85,
    "name": "Abdullah",
    "blood_group": "AB-",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 25,
    "number": "32",
    "address": "Punjab"
  }, {
    "id": 86,
    "name": "Ali",
    "blood_group": "O-",
    "gender": "Male",
    "city": "Multan",
    "age": 13,
    "number": "324",
    "address": "Faisalabad"
  }, {
    "id": 87,
    "name": "Sajawal",
    "blood_group": "O-",
    "gender": "Male",
    "city": "Lahore",
    "age": 20,
    "number": "324",
    "address": "Pakistan"
  }, {
    "id": 88,
    "name": "Ghulam",
    "blood_group": "A+",
    "gender": "Male",
    "city": "Multan",
    "age": 20,
    "number": "4",
    "address": "Pakistan"
  }, {
    "id": 89,
    "name": "Mohsin",
    "blood_group": "A+",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 25,
    "number": "32423",
    "address": "Punjab"
  }, {
    "id": 90,
    "name": "Abdullah",
    "blood_group": "B-",
    "gender": "Male",
    "city": "Karachi",
    "age": 20,
    "number": "3",
    "address": "Pakistan"
  }, {
    "id": 91,
    "name": "Sajawal",
    "blood_group": "O+",
    "gender": "Male",
    "city": "Gujranwala",
    "age": 20,
    "number": "",
    "address": "Faisalabad"
  }, {
    "id": 92,
    "name": "Mohsin",
    "blood_group": "B-",
    "gender": "Male",
    "city": "Islamabad",
    "age": 13,
    "number": "32",
    "address": "Pakistan"
  }, {
    "id": 93,
    "name": "Ahmad",
    "blood_group": "AB+",
    "gender": "Male",
    "city": "Multan",
    "age": 20,
    "number": "",
    "address": "Pakistan"
  }, {
    "id": 94,
    "name": "Ghous",
    "blood_group": "A+",
    "gender": "Male",
    "city": "Faisalabad",
    "age": 25,
    "number": "234",
    "address": "Punjab"
  }, {
    "id": 95,
    "name": "Shary",
    "blood_group": "O-",
    "gender": "Male",
    "city": "Karachi",
    "age": 20,
    "number": "423",
    "address": "Pakistan"
  }, {
    "id": 96,
    "name": "Basit",
    "blood_group": "AB+",
    "gender": "Male",
    "city": "Faisalabad",
    "age": 13,
    "number": "324",
    "address": "Faisalabad"
  }, {
    "id": 97,
    "name": "Waqar",
    "blood_group": "B+",
    "gender": "Male",
    "city": "Rawalpindi",
    "age": 15,
    "number": "8",
    "address": "Punjab"
  }, {
    "id": 98,
    "name": "Ghous",
    "blood_group": "AB-",
    "gender": "Male",
    "city": "Karachi",
    "age": 20,
    "number": "567",
    "address": "Pakistan"
  }, {
    "id": 99,
    "name": "Waqar",
    "blood_group": "O-",
    "gender": "Male",
    "city": "Islamabad",
    "age": 20,
    "number": "867",
    "address": "Pakistan"
  }, {
    "id": 100,
    "name": "Shary",
    "blood_group": "A-",
    "gender": "Male",
    "city": "Rawalpindi",
    "age": 26,
    "number": "324",
    "address": "Faisalabad"
  }]