export const GET_PROFILES = "GET_PROFILES"
export const GET_PROFILES_FAIL = "GET_PROFILES_FAIL"

export const GET_SINGLE_PROFILE = "GET_SINGLE_PROFILE"
export const GET_SINGLE_PROFILE_FAIL = "GET_SINGLE_PROFILE_FAIL"

export const ADD_NEW_PROFILE = "ADD_NEW_PROFILE"
export const ADD_NEW_PROFILE_FAIL = "ADD_NEW_PROFILE_FAIL"

export const LOGIN_AUTH = "LOGIN_AUTH"
export const LOGIN_AUTH_FAIL = "LOGIN_AUTH_FAIL"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL"